Vagrant.configure("2") do |config|

  config.vm.define "server1" do |server1|
    server1.vm.box = "ubuntu/focal64"
    server1.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
    server1.vm.network "public_network", ip: "192.168.0.101"
  end

  config.vm.define "server2" do |server2|
   server2.vm.box = "ubuntu/focal64"
   server2.vm.provider "virtualbox" do |v|
     v.cpus = 2
     v.memory = 2048
   end 
   server2.vm.network "public_network", ip: "192.168.0.102"
  end
end
