Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"

    ubuntu.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 4096
    end
    ubuntu.vm.network "public_network"
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2222
  end
end

